#!usr/bin/python3
def raise_exception():
    x = 5
    result = x + 'a'
